language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"

install:
- pip install -r requirements.txt
- pip install -r tests/requirements.txt

script:
- python -m flake8 --max-line-length=110 tester_alice_skill_flask
- python -m pylint tester_alice_skill_flask
- python -m coverage run tests/test_buy_elephant.py
- python -m coverage report --skip-covered
