language: python
python:
  - "2.7"
  - "3.6"

install:
- pip install -r requirements.txt
- pip install -r tests/requirements.txt

script:
- python -m flake8 --max-line-length=110 tester_alice_skill_flask
