# https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python
name: py2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  py2:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['2.7']

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements2.txt
        pip install -r tests/requirements.txt

    - name: flake8
      run: |
        flake8 --count --show-source --statistics tester_alice_skill_flask
        flake8 --count --show-source --statistics tests/test

    - name: pylint
      run: |
        python -m pylint --rcfile .pylintrc2 tester_alice_skill_flask
        python -m pylint --rcfile .pylintrc2 tests/test

    - name: pytest
      run: |
        pytest --cov=tester_alice_skill_flask --cov-report xml --cov-report term:skip-covered --durations=5 tests
